artifact=app.zyntax.gradle:jansi:1.18-zyntax.1
target=android-aarch64
android.api=24
ndk.revision=29.0.14206865
jansi.version=1.18
jansi.repository=https://github.com/fusesource/jansi.git
jansi.revision=6ca91069e9bb03dadbe1bab58bfd1380ed803547
jansi.native.version=1.8
jansi.native.repository=https://github.com/fusesource/jansi-native.git
jansi.native.revision=5015ad023a55785dbe6ad19cc786c0533387feff
hawtjni.runtime.version=1.17
hawtjni.runtime.repository=https://github.com/fusesource/hawtjni.git
hawtjni.runtime.revision=bb3bdf972b18630cfbc13f890447e0b019719815
hawtjni.generator.version=1.17
hawtjni.generator.url=https://repo.maven.apache.org/maven2/org/fusesource/hawtjni/hawtjni-generator/1.17/hawtjni-generator-1.17.jar
hawtjni.generator.sha256=303a056c0c62bd1606d963271419432d61f509d8e28688278c7fd7d411044025
